server:
  port: 8189

spring:
  kafka:
    bootstrap-servers:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.citi.cbk.entity"

kafka:
  topics:
      name: topic1
      num-partitions: 3
      replication-factor: 1